[New] ability to archive tar ball

diff --git a/wpsync b/wpsync
--- a/wpsync
+++ b/wpsync
@@ -44,18 +44,18 @@ function __help() {
 # Command
 # ----------------------------------------
 
-function _mysqlstore(){
-    . lib/mysql-admin-agent.sh
-    set_wp_path ../../
-	local db_name=$(get_wp_config_value DB_NAME)
-	local db_user=$(get_wp_config_value DB_USER)
-	local db_password=$(get_wp_config_value DB_PASSWORD)
-	local db_host=$(get_wp_config_value DB_HOST)
-	echo ${db_name}
-	echo ${db_user}
-	echo ${db_password}
-	echo ${db_host}
-}
+#function _mysqlstore(){
+#    . lib/mysql-admin-agent.sh
+#    set_wp_path ../../
+#	local db_name=$(get_wp_config_value DB_NAME)
+#	local db_user=$(get_wp_config_value DB_USER)
+#	local db_password=$(get_wp_config_value DB_PASSWORD)
+#	local db_host=$(get_wp_config_value DB_HOST)
+#	echo ${db_name}
+#	echo ${db_user}
+#	echo ${db_password}
+#	echo ${db_host}
+#}
 
 function _mysqldump() {
     if [ -f $(cd $(dirname $0);pwd)/.env ]; then
@@ -64,6 +64,14 @@ function _mysqldump() {
         echo "error: .env file does not exist."
         exit 1
     fi
+
+    if [ $1 != "" ]; then
+        download_dump_file_path=$1
+    else
+        download_dump_file_path=$(cd $(dirname $0);pwd)/data/db_dump.sql.tar.gz
+    fi
+
+    dump_file_path=${wp_root}/.db-dump/db-dump.sql
     
     # UPLOAD mysql-admin-agent.sh
     echo ">>> upload mysql-admin-agent.sh..."
@@ -81,28 +89,30 @@ function _mysqldump() {
     
     # DUMP MYSQL DATA
     if [ ! -z ${wp_host} ]; then
-        ssh x sh ${wp_root}/mysql-admin-agent.sh db_dump || {
+        ssh x sh ${wp_root}/mysql-admin-agent.sh db_dump true || {
             echo "error."
             exit 1
         }
     else
-        ssh -p ${ssh_port} ${ssh_user}@${ssh_host} sh ${wp_root}/mysql-admin-agent.sh db_dump || {
+        ssh -p ${ssh_port} ${ssh_user}@${ssh_host} sh ${wp_root}/mysql-admin-agent.sh db_dump true || {
             echo "error."
             exit 1
         }
     fi
-    
+
     # DOWNLOAD DUMP DATA
     echo ">>> download dump data..."
     mkdir -p $(cd $(dirname $0);pwd)/data
 
     if [ ! -z ${wp_host} ]; then
-        scp ${wp_host}:${wp_root}/.backup/db-dump.sql $(cd $(dirname $0);pwd)/data/db_dump.sql || {
+        #scp ${wp_host}:${wp_root}/.db-dump//db-dump.sql $(cd $(dirname $0);pwd)/data/db_dump.sql || {
+        scp ${wp_host}:${dump_file_path}.tar.gz ${download_dump_file_path} || {
             echo "error."
             exit 1
         }
     else
-        scp -P ${ssh_port} ${ssh_user}@${ssh_host}:${wp_root}/.backup/db-dump.sql $(cd $(dirname $0);pwd)/data/db-dump.sql || {
+        #scp -P ${ssh_port} ${ssh_user}@${ssh_host}:${wp_root}/.db-dump/db-dump.sql $(cd $(dirname $0);pwd)/data/db-dump.sql || {
+        scp -P ${ssh_port} ${ssh_user}@${ssh_host}:${dump_file_path}.tar.gz ${download_dump_file_path} || {
             echo "error."
             exit 1
         }
@@ -113,13 +123,13 @@ function _mysqldump() {
     if [ ! -z ${wp_host} ]; then
         #ssh -t -t x <<EOF
         ssh x <<EOF > /dev/null 2>&1
-rm -rf ${wp_root}/.backup
+rm -rf ${wp_root}/.db-dump
 rm -rf ${wp_root}/mysql-admin-agent.sh
 exit
 EOF
     else
         ssh -p ${ssh_port} ${ssh_user}@${ssh_host} <<EOF > /dev/null 2>&1
-rm -rf ${wp_root}/.backup
+rm -rf ${wp_root}/.db-dump
 rm -rf ${wp_root}/mysql-admin-agent.sh
 exit
 EOF
@@ -143,7 +153,7 @@ done
 shift $(expr $OPTIND - 1)
 
 # check argument(s)
-if [ $# -ne 1 ]; then
+if [ $# -eq 0 ]; then
     echo "error: invalid argument(s)"
     echo "See '${project_name} -h'." 
     exit 1
@@ -151,9 +161,10 @@ fi
 
 # execute command
 if __is_executable _$1; then
-    _$1
+    cmd=$1; shift
+    _${cmd} $@
 else
-    echo "error: invalid argument(s)"
+    echo "error: not executable."
     echo "See '${project_name} -h'." 
     exit 1
 fi
